// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package database

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, name, created_at, updated_at, apikey)
VALUES (?, ?, ?, ?, ?
)
`

type CreateUserParams struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Apikey    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Apikey,
	)
	return err
}

const getUserByAPIKey = `-- name: GetUserByAPIKey :one
SELECT id, name, created_at, updated_at, apikey FROM users WHERE apikey = ?
`

func (q *Queries) GetUserByAPIKey(ctx context.Context, apikey string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByAPIKey, apikey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Apikey,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, created_at, updated_at, apikey FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Apikey,
	)
	return i, err
}
